#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Nov 20 10:46:08 2022

@author: victoriaonyon
"""

 # This is my first line of python code in Spyder
# Create a list and print the integers of 1 - 10 inclusive

integers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

print(integers)